uglifyjs \
  $1_settings.js \
  camera.js \
  d3sprigbridge.js \
  uid.js \
  apienvoy.js \
  okcanceldialog.js \
  store.js \
  treerenderer.js \
  treenav.js \
  collisionfinder.js \
  graph.js \
  textstuff.js \
  divider.js \
  historian.js \
  load_a_typekit.js \
  ../node_modules/strokerouter/strokerouter.js \
  spriglog.js \
  sprigotbasemixin.js \
  sprigot.js \
  newdoc.js \
  direct.js \
 -c -m -o ~/gcw/$1/sprigotclient.js
